version: "3.9"
########################### NETWORKS
networks:
  db_net:
    name: db_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24
########################### SECRETS
secrets:
  redisconf:
    file: $SECRETDIR/redisconf
  mysql_root_password:
    file: $SECRETDIR/mysql_root_password
########################### SERVICES
services:
 ############################# DATABASE

  # MariaDB - MySQL Database
  # After starting container for first time dexec and mysqladmin -u root password <password>
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    restart: always
    # profiles:
    # - core
    #read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - db_net
    volumes:
      - /mnt/data/db/mariadb:/config
      - /run
    environment:
      - PUID=$DOCKERRUNNER
      - PGID=$DOCKERFILES
      - TZ=$TZ
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password # Note FILE__ (double underscore) - Issue #127
    secrets:
      - mysql_root_password
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://newreleases.io/linuxserver/docker-mariadb
      - wud.watch.digest=true
  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:7.2.4
    restart: always
    secrets:
      - redisconf
    # profiles:
    # - core
    entrypoint: redis-server /run/secrets/redisconf
    networks:
      - db_net
    user: $DOCKERRUNNER:$DOCKERFILES
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - /mnt/data/db/redis/data:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    labels:
      - wud.link.template=https://newreleases.io/dockerhub/redis
      - wud.watch.digest=true
      - wud.tag.include=^\d+\.\d+\.\d+$$