version: "3.9"
########################### NETWORKS
networks:
  cloudflare-proxy:
    name: cloudflare-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24
  recipe_db:
########################### SECRETS

########################### SERVICES
services:
  httpEcho:
    container_name: http_echo
    image: mendhak/http-https-echo:33
    restart: always
    user: $DOCKERRUNNER:$DOCKERFILES
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
        - HTTP_PORT=8888
    volumes:
      - /var/cache
      - /var/run
    labels: # traefik example labels
      - "traefik.enable=true"
      - "traefik.http.routers.http-echo.rule=Host(`echo.$DOMAINNAME0`, `www.echo.$DOMAINNAME0`)"
      - "traefik.http.routers.http-echo.entrypoints=https" # your https endpoint
      ## Middlewares
      - "traefik.http.routers.http-echo.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.http-echo.service=http-echo-svc"
      - "traefik.http.services.http-echo-svc.loadbalancer.server.port=8888"
    networks:
      - net-t2-proxy
      - cloudflare-proxy
  cloudflared:
    container_name: cloudflared
    image: erisamoe/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - $SECRETDIR/cloudflared.env
    networks:
      - cloudflare-proxy